name: Auto Comment on Issue Opened

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              ## 👋 Thanks for Opening an Issue! 🎉

              We appreciate your contribution. Our team will review this issue within **5–8 hours**.

              **Important Notes:**
              - 🔒 Please **do not raise a PR unless this issue is assigned to you**.
              - 📝 Ensure you provide **all necessary details**, including screenshots or video demos if possible — this helps us review and assign issues faster.

              **Need Help?**
              - Reach out on [LinkedIn](https://www.linkedin.com/in/sanjay-k-v/).
              - We actively maintain this repo twice a day at **8:00 AM IST** and **9:00 PM IST**.  
                If your issue goes stale for more than 24 hours, feel free to **tag `@sanjay-kv`** in a comment.

              **✨ Bonus:**  
              Consistent contributors are eligible for **sponsorships**. Check out our amazing [sponsors here](https://www.recodehive.com/our-sponsors).  

              _Thanks for being a part of our open-source journey!_ 🚀
              `
            });
